"use client";
import { useState } from "react";

// ─── Helpers ────────────────────────────────────────────────────────────────

function getDomain(url: string): string {
  try { return new URL(url).hostname; } catch { return url; }
}

function calcEntropy(str: string): number {
  const freq: Record<string, number> = {};
  for (const c of str) freq[c] = (freq[c] || 0) + 1;
  return -Object.values(freq).reduce((sum, f) => {
    const p = f / str.length;
    return sum + p * Math.log2(p);
  }, 0);
}

function countSubdomains(url: string): number {
  return getDomain(url).split(".").length - 2;
}

function countSpecialChars(url: string): number {
  return (url.match(/[@%#~]/g) || []).length;
}

function hasLookalikeTrick(url: string): boolean {
  const domain = getDomain(url).toLowerCase();
  const brands = ["paypal","amazon","google","facebook","microsoft","apple","netflix","instagram","twitter","linkedin","whatsapp","ebay","bank","chase","wellsfargo","citibank"];
  const normalized = domain.replace(/0/g,"o").replace(/1/g,"l").replace(/3/g,"e").replace(/4/g,"a").replace(/5/g,"s");
  return brands.some(b => normalized.includes(b) && !domain.includes(b));
}

function hasAtSymbolTrick(url: string): boolean {
  try { return new URL(url).username !== "" || url.includes("@"); }
  catch { return url.includes("@"); }
}

function hasExcessiveDots(url: string): boolean {
  return (getDomain(url).match(/\./g) || []).length >= 4;
}

function hasNumericSubdomain(url: string): boolean {
  return getDomain(url).split(".").some(p => /^[a-z]{0,2}\d{5,}$/.test(p));
}

function isEmailTrackingAbuse(url: string): boolean {
  return ["sendgrid.net","ct.sendgrid","mailchimp.com","list-manage.com","mandrillapp.com","emltrk.com","click.mlsend","trk.","r.mail.","email.mg."]
    .some(s => url.toLowerCase().includes(s));
}

function isAutoGeneratedDomain(url: string): boolean {
  const domain = getDomain(url).split(".")[0];
  return /\d{5,}/.test(domain) || (/[a-z]\d{3,}/.test(domain) && domain.length > 8);
}

function hasEncodedHiddenURL(url: string): boolean {
  return (url.match(/-2F|-2B|-3D|-2C|-3A/gi) || []).length >= 3;
}

function hasNestedURL(url: string): boolean {
  try {
    const params = new URL(url).search;
    return /upn=|url=|u=|link=/.test(params) && params.length > 50;
  } catch { return false; }
}

function isClickTrackingPath(url: string): boolean {
  const paths = ["/ls/click","/click","/track/click","/wf/click","/c/","/l/","/lt.php","/click.php","/go/","/redirect","/r/","/out/"];
  try {
    const path = new URL(url).pathname.toLowerCase();
    return paths.some(p => path.startsWith(p) || path === p);
  } catch { return false; }
}

function hasSuspiciousParams(url: string): boolean {
  try {
    const params = new URL(url).search.toLowerCase();
    const suspicious = ["upn=","u=","url=","link=","dest=","goto=","target=","redir=","ref="];
    return suspicious.filter(p => params.includes(p)).length >= 1 && params.length > 80;
  } catch { return false; }
}

function hasMultipleRedirects(url: string): boolean {
  const redirectParams = ["redirect=","url=","next=","dest=","goto=","link=","target="];
  return redirectParams.filter(p => url.toLowerCase().includes(p)).length >= 2;
}

function isSendGridRedirectAbuse(url: string): boolean {
  const isTracking = ["sendgrid.net","ct.sendgrid","mailchimp.com","list-manage.com"]
    .some(s => url.toLowerCase().includes(s));
  let isClick = false;
  try {
    const pn = new URL(url).pathname.toLowerCase();
    isClick = ["/ls/click","/click","/track/click"].some(p => pn.startsWith(p));
  } catch {}
  return isTracking && isClick;
}

// ─── All 35 Tests ────────────────────────────────────────────────────────────

type Severity = "Critical" | "High" | "Medium" | "Low";

interface Test {
  name: string;
  description: string;
  severity: Severity;
  weight: number;
  check: (url: string) => boolean;
}

const TESTS: Test[] = [
  {
    name: "SQL Injection",
    description: "Tests for SQL injection vulnerabilities in URL parameters",
    severity: "Critical", weight: 25,
    check: (url) => ["'", '"', "or 1=1", "union select"].some(p => url.toLowerCase().includes(p)),
  },
  {
    name: "XSS (Cross-Site Scripting)",
    description: "Checks for potential XSS vulnerabilities",
    severity: "High", weight: 20,
    check: (url) => ["<script", "javascript:", "onerror=", "onload="].some(p => url.toLowerCase().includes(p)),
  },
  {
    name: "HTTPS / SSL Check",
    description: "Verifies if the site uses HTTPS",
    severity: "Medium", weight: 10,
    check: (url) => !url.startsWith("https://"),
  },
  {
    name: "Directory Traversal",
    description: "Tests for directory traversal attempts",
    severity: "High", weight: 20,
    check: (url) => ["../", "..\\", "%2e%2e"].some(p => url.toLowerCase().includes(p)),
  },
  {
    name: "Command Injection",
    description: "Checks for command injection patterns",
    severity: "Critical", weight: 25,
    check: (url) => ["|", ";", "&&", "`", "$(", "%7C"].some(p => url.includes(p)),
  },
  {
    name: "Open Redirect",
    description: "Looks for open redirect vulnerabilities",
    severity: "Medium", weight: 10,
    check: (url) => ["redirect=", "next=", "return=", "dest=", "goto="].some(p => url.toLowerCase().includes(p)),
  },
  {
    name: "URL Shortener",
    description: "Detects URL shorteners that may hide malicious destinations",
    severity: "Medium", weight: 10,
    check: (url) => ["bit.ly","tinyurl.com","t.co","goo.gl","ow.ly","short.io","tiny.cc","rb.gy","is.gd","buff.ly","ift.tt"].some(s => url.includes(s)),
  },
  {
    name: "IP Address URL",
    description: "Detects URLs using raw IP addresses instead of domain names",
    severity: "High", weight: 18,
    check: (url) => /https?:\/\/\d+\.\d+\.\d+\.\d+/.test(url),
  },
  {
    name: "Fake Domain (Typosquatting)",
    description: "Detects typosquatted or fake domains impersonating popular sites",
    severity: "Critical", weight: 25,
    check: (url) => ["paypa1","paypai","arnazon","amazom","g00gle","googie","faceb00k","facebok","micros0ft","microsft","app1e","netfl1x","lnstagram","instagran","twltter","twitterr","linkedln","whatsaap","discrod"].some(f => url.toLowerCase().includes(f)),
  },
  {
    name: "Phishing Keywords",
    description: "Detects common phishing keywords used to trick users",
    severity: "High", weight: 20,
    check: (url) => ["login-verify","account-suspended","verify-now","update-billing","confirm-identity","secure-login","account-locked","unusual-activity","verify-account","password-reset","webscr","ebayisapi","signin-","-secure","banking-","customer-service"].some(k => url.toLowerCase().includes(k)),
  },
  {
    name: "Suspicious TLD",
    description: "Detects top-level domains commonly abused in malicious sites",
    severity: "Medium", weight: 12,
    check: (url) => {
      const domain = getDomain(url);
      return [".xyz",".top",".club",".work",".click",".loan",".gq",".ml",".cf",".tk",".pw",".cc",".ru",".cn",".info"].some(t => domain.endsWith(t));
    },
  },
  {
    name: "Data Theft Patterns",
    description: "Detects parameters used to steal sensitive data like passwords or card info",
    severity: "Critical", weight: 25,
    check: (url) => ["passwd=","password=","creditcard=","ssn=","cvv=","bankaccount=","cardnumber=","pin="].some(p => url.toLowerCase().includes(p)),
  },
  {
    name: "Excessive URL Length",
    description: "Very long URLs (over 200 chars) are often used to hide malicious content",
    severity: "Medium", weight: 8,
    check: (url) => url.length > 200,
  },
  {
    name: "High URL Entropy",
    description: "Highly random URLs indicate automated phishing generation",
    severity: "High", weight: 18,
    check: (url) => calcEntropy(getDomain(url)) > 3.8,
  },
  {
    name: "Excessive Subdomains",
    description: "Too many subdomains are used to mimic legitimate sites",
    severity: "High", weight: 15,
    check: (url) => countSubdomains(url) >= 3,
  },
  {
    name: "Special Characters in URL",
    description: "Unusual characters like @, %, # used to disguise malicious URLs",
    severity: "Medium", weight: 10,
    check: (url) => countSpecialChars(url) >= 3,
  },
  {
    name: "Brand Name in Subdomain",
    description: "Phishers add real brand names as subdomains to trick users",
    severity: "Critical", weight: 25,
    check: (url) => {
      const brands = ["paypal","amazon","google","facebook","microsoft","apple","netflix","instagram","twitter","linkedin","whatsapp","bank","ebay"];
      try {
        const u = new URL(url);
        const subdomain = u.hostname.split(".").slice(0, -2).join(".");
        return brands.some(b => subdomain.includes(b));
      } catch { return false; }
    },
  },
  {
    name: "Deep URL Path",
    description: "Very deep file paths are used by attackers to hide phishing pages",
    severity: "Medium", weight: 8,
    check: (url) => {
      try { return new URL(url).pathname.split("/").length > 6; }
      catch { return false; }
    },
  },
  {
    name: "Number-for-Letter Substitution",
    description: "Replaces letters with numbers to fake brand names (paypa1, g00gle)",
    severity: "Critical", weight: 25,
    check: (url) => hasLookalikeTrick(url),
  },
  {
    name: "@ Symbol Trick",
    description: "URLs with @ symbol trick browsers into visiting malicious domains",
    severity: "Critical", weight: 22,
    check: (url) => hasAtSymbolTrick(url),
  },
  {
    name: "Excessive Dots in Domain",
    description: "Too many dots used to hide the real malicious domain",
    severity: "High", weight: 15,
    check: (url) => hasExcessiveDots(url),
  },
  {
    name: "Hex / Encoded Characters",
    description: "Encoded characters used to disguise malicious URLs from filters",
    severity: "High", weight: 15,
    check: (url) => (url.match(/%[0-9a-fA-F]{2}/g) || []).length >= 3,
  },
  {
    name: "Suspicious File Extension",
    description: "Links to executable or dangerous file types",
    severity: "Critical", weight: 25,
    check: (url) => [".exe",".bat",".cmd",".ps1",".vbs",".scr",".msi",".jar",".php?"].some(e => url.toLowerCase().includes(e)),
  },
  {
    name: "Free Hosting Platform",
    description: "Free hosting services commonly abused for phishing pages",
    severity: "High", weight: 18,
    check: (url) => ["000webhostapp.com","weebly.com","wixsite.com","glitch.me","web.app","firebaseapp.com","github.io","netlify.app","vercel.app","pages.dev"].some(h => url.toLowerCase().includes(h)),
  },
  {
    name: "Urgency Words in URL",
    description: "Urgency words used to pressure users into clicking malicious links",
    severity: "High", weight: 15,
    check: (url) => ["urgent","immediate","alert","warning","suspended","blocked","limited","expire","critical","action-required","act-now","final-notice"].some(w => url.toLowerCase().includes(w)),
  },
  {
    name: "Email Tracking Service Abuse",
    description: "Phishers use SendGrid, Mailchimp and similar services to hide malicious links",
    severity: "High", weight: 18,
    check: (url) => isEmailTrackingAbuse(url),
  },
  {
    name: "Numeric / Auto-Generated Subdomain",
    description: "Long numeric subdomains like u29698972.ct.sendgrid.net indicate auto-generated phishing URLs",
    severity: "High", weight: 15,
    check: (url) => hasNumericSubdomain(url),
  },
  {
    name: "Auto-Generated Domain",
    description: "Domains with long number sequences are auto-generated for phishing campaigns",
    severity: "Critical", weight: 22,
    check: (url) => isAutoGeneratedDomain(url),
  },
  {
    name: "Long Query String",
    description: "Extremely long query parameters used to hide redirect destinations",
    severity: "Medium", weight: 8,
    check: (url) => {
      try { return new URL(url).search.length > 200; } catch { return false; }
    },
  },
  {
    name: "Multiple Redirects in URL",
    description: "URL contains multiple redirect parameters chained together",
    severity: "High", weight: 18,
    check: (url) => hasMultipleRedirects(url),
  },
  {
    name: "Suspicious Redirect Parameter",
    description: "URL has suspicious redirect/tracking parameters with long values",
    severity: "High", weight: 15,
    check: (url) => hasSuspiciousParams(url),
  },
  {
    name: "SendGrid Redirect Abuse",
    description: "Detects phishing emails routed through legitimate email services",
    severity: "Critical", weight: 22,
    check: (url) => isSendGridRedirectAbuse(url),
  },
  {
    name: "Encoded Hidden URL",
    description: "SendGrid-style encoded URLs hiding malicious destinations",
    severity: "High", weight: 18,
    check: (url) => hasEncodedHiddenURL(url),
  },
  {
    name: "Nested URL in Parameter",
    description: "A full URL hidden inside a query parameter — classic redirect abuse",
    severity: "High", weight: 18,
    check: (url) => hasNestedURL(url),
  },
  {
    name: "Click Tracking Path",
    description: "URL path matches known click-tracking endpoints used in phishing emails",
    severity: "Medium", weight: 12,
    check: (url) => isClickTrackingPath(url),
  },
];

// ─── Severity config ─────────────────────────────────────────────────────────

const severityConfig: Record<Severity, { bg: string; text: string; border: string; badge: string }> = {
  Critical: { bg: "bg-red-50",     text: "text-red-600",     border: "border-red-200",     badge: "bg-red-100 text-red-700 border-red-300"     },
  High:     { bg: "bg-orange-50",  text: "text-orange-600",  border: "border-orange-200",  badge: "bg-orange-100 text-orange-700 border-orange-300"  },
  Medium:   { bg: "bg-amber-50",   text: "text-amber-600",   border: "border-amber-200",   badge: "bg-amber-100 text-amber-700 border-amber-300"   },
  Low:      { bg: "bg-emerald-50", text: "text-emerald-600", border: "border-emerald-200", badge: "bg-emerald-100 text-emerald-700 border-emerald-300" },
};

// ─── Risk band ───────────────────────────────────────────────────────────────

interface RiskBand {
  label: string;
  color: string;
  glow: string;
  bg: string;
  border: string;
}

function getRiskBand(score: number): RiskBand {
  if (score === 0)  return { label: "Safe",        color: "#10b981", glow: "shadow-emerald-200", bg: "bg-emerald-50",  border: "border-emerald-200" };
  if (score <= 25)  return { label: "Low Risk",    color: "#f59e0b", glow: "shadow-amber-200",   bg: "bg-amber-50",    border: "border-amber-200"   };
  if (score <= 55)  return { label: "Medium Risk", color: "#f97316", glow: "shadow-orange-200",  bg: "bg-orange-50",   border: "border-orange-200"  };
  if (score <= 80)  return { label: "High Risk",   color: "#ef4444", glow: "shadow-red-200",     bg: "bg-red-50",      border: "border-red-200"     };
  return                    { label: "Critical",   color: "#991b1b", glow: "shadow-red-300",     bg: "bg-red-100",     border: "border-red-300"     };
}

// ─── Riskometer ──────────────────────────────────────────────────────────────

function Riskometer({ score, band }: { score: number; band: RiskBand }) {
  const cx = 110, cy = 100, r = 80;
  const angle = 180 - (score / 100) * 180;
  const rad = (angle * Math.PI) / 180;
  const needleLength = 68;
  const nx = cx + needleLength * Math.cos(rad);
  const ny = cy - needleLength * Math.sin(rad);

  function arcPath(startPct: number, endPct: number, radius: number) {
    const s = (startPct / 100) * Math.PI;
    const e = (endPct / 100) * Math.PI;
    const x1 = cx + radius * Math.cos(Math.PI - s);
    const y1 = cy - radius * Math.sin(Math.PI - s);
    const x2 = cx + radius * Math.cos(Math.PI - e);
    const y2 = cy - radius * Math.sin(Math.PI - e);
    const large = endPct - startPct > 50 ? 1 : 0;
    return `M ${x1} ${y1} A ${radius} ${radius} 0 ${large} 1 ${x2} ${y2}`;
  }

  const segments = [
    { start: 0,  end: 25,  color: "#10b981" },
    { start: 25, end: 55,  color: "#f59e0b" },
    { start: 55, end: 80,  color: "#f97316" },
    { start: 80, end: 100, color: "#ef4444" },
  ];

  return (
    <svg viewBox="0 0 220 115" className="w-full max-w-[260px]" aria-label={`Threat score ${score}`}>
      <path d={arcPath(0, 100, r)} fill="none" stroke="#e2e8f0" strokeWidth="14" strokeLinecap="round" />
      {segments.map((seg) => (
        <path key={seg.color} d={arcPath(seg.start, seg.end, r)} fill="none" stroke={seg.color} strokeWidth="14" strokeLinecap="butt" opacity="0.35" />
      ))}
      {score > 0 && (
        <path d={arcPath(0, score, r)} fill="none" stroke={band.color} strokeWidth="14" strokeLinecap="round" />
      )}
      {[0, 25, 55, 80, 100].map((tick) => {
        const tr = (tick / 100) * Math.PI;
        const innerR = r - 10, outerR = r + 4;
        const tx1 = cx + innerR * Math.cos(Math.PI - tr);
        const ty1 = cy - innerR * Math.sin(Math.PI - tr);
        const tx2 = cx + outerR * Math.cos(Math.PI - tr);
        const ty2 = cy - outerR * Math.sin(Math.PI - tr);
        return <line key={tick} x1={tx1} y1={ty1} x2={tx2} y2={ty2} stroke="#cbd5e1" strokeWidth="1.5" />;
      })}
      <line x1={cx} y1={cy} x2={nx} y2={ny} stroke={band.color} strokeWidth="3" strokeLinecap="round" />
      <circle cx={cx} cy={cy} r="6" fill={band.color} />
      <circle cx={cx} cy={cy} r="3" fill="white" />
      <text x={cx} y={cy - 18} textAnchor="middle" fontSize="22" fontWeight="800" fill={band.color} fontFamily="system-ui, sans-serif">{score}</text>
      <text x={cx} y={cy - 5} textAnchor="middle" fontSize="7" fill="#94a3b8" fontFamily="system-ui, sans-serif" letterSpacing="1">THREAT SCORE</text>
      <text x="16" y="112" fontSize="7" fill="#94a3b8" fontFamily="system-ui, sans-serif">Safe</text>
      <text x="192" y="112" fontSize="7" fill="#94a3b8" textAnchor="end" fontFamily="system-ui, sans-serif">Critical</text>
    </svg>
  );
}

// ─── Result type ─────────────────────────────────────────────────────────────

interface Result {
  name: string;
  description: string;
  severity: Severity;
  weight: number;
  vulnerable: boolean;
}

function computeThreatScore(results: Result[]): number {
  const maxScore = TESTS.reduce((sum, t) => sum + t.weight, 0);
  const hitScore = results.filter((r) => r.vulnerable).reduce((sum, r) => sum + r.weight, 0);
  return Math.min(100, Math.round((hitScore / maxScore) * 100));
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function URLScanner() {
  const [url, setUrl] = useState("");
  const [results, setResults] = useState<Result[]>([]);
  const [scanning, setScanning] = useState(false);
  const [scanned, setScanned] = useState(false);
  const [filter, setFilter] = useState<"all" | "vulnerable" | "safe">("all");

  function scan() {
    if (!url.trim()) return;
    setScanning(true);
    setScanned(false);
    setResults([]);
    setFilter("all");
    setTimeout(() => {
      const res: Result[] = TESTS.map((t) => ({
        name: t.name,
        description: t.description,
        severity: t.severity,
        weight: t.weight,
        vulnerable: (() => { try { return t.check(url.trim()); } catch { return false; } })(),
      }));
      setResults(res);
      setScanning(false);
      setScanned(true);
    }, 900);
  }

  const total = results.length;
  const vulnCount = results.filter((r) => r.vulnerable).length;
  const safeCount = total - vulnCount;
  const threatScore = computeThreatScore(results);
  const band = getRiskBand(threatScore);

  const displayed =
    filter === "all" ? results :
    filter === "vulnerable" ? results.filter((r) => r.vulnerable) :
    results.filter((r) => !r.vulnerable);

  return (
    <section id="scanner" className="py-24 px-6 bg-white">
      <div className="max-w-4xl mx-auto">

        {/* Header */}
        <div className="text-center mb-12">
          <span className="inline-block text-xs font-bold tracking-widest uppercase text-[#0ea5e9] mb-4">
            Live Scanner
          </span>
          <h2 className="text-4xl md:text-5xl font-extrabold text-[#0f172a] mb-5 tracking-tight">
            Scan any URL{" "}
            <span className="gradient-text">right now</span>
          </h2>
          <p className="max-w-xl mx-auto text-lg text-[#64748b] leading-relaxed">
            Paste a suspicious URL and get an instant threat score across{" "}
            <strong className="text-[#0f172a]">35 vulnerability checks</strong>.
          </p>
        </div>

        {/* Input box */}
        <div className="bg-[#f7f4ef] rounded-2xl border border-[#ddd8cf] p-6 mb-8">
          <label className="block text-sm font-semibold text-[#0f172a] mb-2">URL to scan</label>
          <div className="flex gap-3 flex-col sm:flex-row">
            <input
              type="text"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && !scanning && scan()}
              placeholder="https://example.com?id=1"
              className="flex-1 px-4 py-3 rounded-xl border border-[#ddd8cf] bg-white text-[#0f172a] placeholder-[#94a3b8] focus:outline-none focus:ring-2 focus:ring-[#0ea5e9]/40 focus:border-[#0ea5e9] text-sm font-mono transition-all"
            />
            <button
              onClick={scan}
              disabled={scanning || !url.trim()}
              className="px-6 py-3 rounded-xl bg-[#0f172a] text-white font-semibold text-sm hover:bg-[#1e3a5f] disabled:opacity-40 disabled:cursor-not-allowed transition-all flex items-center gap-2 justify-center whitespace-nowrap"
            >
              {scanning ? (
                <>
                  <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                    <circle cx="12" cy="12" r="10" stroke="white" strokeWidth="3" strokeDasharray="30 60" />
                  </svg>
                  Scanning...
                </>
              ) : (
                <>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <circle cx="11" cy="11" r="8" />
                    <path d="M21 21l-4.35-4.35" strokeLinecap="round" />
                  </svg>
                  Scan URL
                </>
              )}
            </button>
          </div>
          <p className="text-xs text-[#94a3b8] mt-2">
            Try:{" "}
            <button
              onClick={() => setUrl("http://paypa1.com/login-verify?passwd=abc")}
              className="bg-white px-1.5 py-0.5 rounded border border-[#ddd8cf] text-[#0ea5e9] font-mono hover:bg-[#f0f9ff] transition-colors"
            >
              http://paypa1.com/login-verify?passwd=abc
            </button>
          </p>
        </div>

        {/* Scanning animation */}
        {scanning && (
          <div className="flex flex-col items-center gap-4 py-12">
            <div className="relative w-16 h-16">
              <div className="absolute inset-0 rounded-full bg-[#0ea5e9]/20 animate-ping" />
              <div className="relative w-16 h-16 rounded-full bg-[#0f172a] flex items-center justify-center">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
                  <path d="M12 2L3 7v5c0 5.25 3.75 10.15 9 11.35C17.25 22.15 21 17.25 21 12V7l-9-5z" fill="#0ea5e9" />
                </svg>
              </div>
            </div>
            <div className="text-center">
              <div className="text-[#0f172a] font-semibold">Analyzing URL...</div>
              <div className="text-[#94a3b8] text-sm mt-1">Running 35 threat checks</div>
            </div>
          </div>
        )}

        {/* Results */}
        {scanned && !scanning && (
          <div className="space-y-6">

            {/* Riskometer + stat cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className={`rounded-2xl border p-6 flex flex-col items-center justify-center ${band.bg} ${band.border}`}>
                <Riskometer score={threatScore} band={band} />
                <div className="mt-2 text-lg font-black tracking-tight" style={{ color: band.color }}>
                  {band.label}
                </div>
                <div className="text-xs text-[#64748b] mt-0.5">Overall Threat Level</div>
              </div>

              <div className="grid grid-cols-2 gap-3 content-start">
                <div className="bg-[#f7f4ef] border border-[#ddd8cf] rounded-2xl p-4 text-center">
                  <div className="text-3xl font-black text-[#0f172a]">{total}</div>
                  <div className="text-xs text-[#64748b] mt-1 font-medium">Total Checks</div>
                </div>
                <div className="bg-red-50 border border-red-100 rounded-2xl p-4 text-center">
                  <div className="text-3xl font-black text-red-500">{vulnCount}</div>
                  <div className="text-xs text-red-400 mt-1 font-medium">Threats Found</div>
                </div>
                <div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-4 text-center">
                  <div className="text-3xl font-black text-emerald-600">{safeCount}</div>
                  <div className="text-xs text-emerald-500 mt-1 font-medium">Passed</div>
                </div>
                <div className={`rounded-2xl p-4 text-center border ${band.bg} ${band.border}`}>
                  <div className="text-3xl font-black" style={{ color: band.color }}>{threatScore}</div>
                  <div className="text-xs text-[#64748b] mt-1 font-medium">Threat Score</div>
                </div>
              </div>
            </div>

            {/* Progress bar */}
            <div className="bg-[#f7f4ef] border border-[#ddd8cf] rounded-2xl p-4">
              <div className="flex justify-between text-xs font-semibold text-[#64748b] mb-2">
                <span>Threat Score</span>
                <span style={{ color: band.color }}>{threatScore} / 100</span>
              </div>
              <div className="h-3 bg-[#e2e8f0] rounded-full overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${threatScore}%`, backgroundColor: band.color }}
                />
              </div>
              <div className="flex justify-between text-[10px] text-[#94a3b8] mt-1">
                <span>Safe</span><span>Low</span><span>Medium</span><span>High</span><span>Critical</span>
              </div>
            </div>

            {/* Filter tabs */}
            <div className="flex gap-2 flex-wrap">
              {(["all", "vulnerable", "safe"] as const).map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`px-4 py-1.5 rounded-full text-xs font-semibold transition-all capitalize ${
                    filter === f
                      ? "bg-[#0f172a] text-white"
                      : "bg-[#f7f4ef] text-[#64748b] border border-[#ddd8cf] hover:bg-[#eee8df]"
                  }`}
                >
                  {f === "all" ? `All (${total})` : f === "vulnerable" ? `Threats (${vulnCount})` : `Safe (${safeCount})`}
                </button>
              ))}
            </div>

            {/* Result cards */}
            <div className="space-y-3">
              {displayed.map((r) => {
                const sev = severityConfig[r.severity];
                return (
                  <div
                    key={r.name}
                    className={`flex items-center gap-4 bg-white border rounded-xl px-5 py-4 shadow-sm transition-all ${
                      r.vulnerable
                        ? "border-l-4 border-l-red-400 border-[#f3e8e8]"
                        : "border-[#ddd8cf]"
                    }`}
                  >
                    {/* Status icon */}
                    <div className={`w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center ${r.vulnerable ? "bg-red-100" : "bg-emerald-100"}`}>
                      {r.vulnerable ? (
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2.5">
                          <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
                          <line x1="12" y1="9" x2="12" y2="13" strokeLinecap="round" />
                          <line x1="12" y1="17" x2="12.01" y2="17" strokeLinecap="round" />
                        </svg>
                      ) : (
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="2.5">
                          <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      )}
                    </div>

                    {/* Name + description */}
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-semibold text-[#0f172a] truncate">{r.name}</div>
                      <div className="text-xs text-[#64748b] mt-0.5 truncate">{r.description}</div>
                    </div>

                    {/* Badges */}
                    <div className="flex flex-col items-end gap-1.5 flex-shrink-0">
                      <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full border ${sev.badge}`}>
                        {r.severity}
                      </span>
                      <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full border ${
                        r.vulnerable
                          ? "bg-red-50 text-red-500 border-red-200"
                          : "bg-emerald-50 text-emerald-600 border-emerald-200"
                      }`}>
                        {r.vulnerable ? "Threat" : "Safe"}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Empty state for filter */}
            {displayed.length === 0 && (
              <div className="text-center py-10 text-[#94a3b8] text-sm">
                No {filter === "vulnerable" ? "threats" : "safe checks"} found.
              </div>
            )}

          </div>
        )}
      </div>
    </section>
  );
}